namespace VCO.Overworld
{
    internal enum TerrainType
    {
        None,
        Grass,
        Moss,
        Stone,
        Wood,
        Metal,
        HollowMetal,
        Dirt,
        Sand,
        Glass,
        Snow,
        Water,
        DeepWater,
        Ocean,
        Sludge,
        DeepSludge,
        Tile,
        StairsLeft,
        StairsRight,
        Ladder,
        Rope,
        SlideLeft,
        SlideRight
    }
}