namespace VCO.Battle
{
    internal enum StatusEffect
    {
        Invalid,
        Talking,
        Sleep,
        Cold,
        Crying,
        Diamondized,
        FeelingStrange,
        Homesick,
        Mushroomized,
        Nausea,
        Paralyzed,
        Poisoned,
        Possessed,
        Solidified,
        Sunstroke,
        Unconscious,
        Shield,
        AUXShield,
        Counter,
        AUXCounter,
        Eraser,
        OffenseUp,
        OffenseDown,
        DefenseUp,
        DefenseDown,
        QuickUp,
        QuickDown,
        DisableAUX,
        Infection
    }
}